/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlehorasvoo;

import static java.lang.System.out;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anonymous
 */
public class Util extends javax.swing.JFrame {

    private Connection connection;
    private ImageIcon icon = new ImageIcon("C:\\Users\\anonymous\\Documents\\NetBeansProjects\\controleHorasVoo\\src\\controlehorasvoo\\JRM.jpg");
    
    /**
     * Creates new form Util
     */
    public Util() {  
        initComponents();
        jLabel15.setIcon(icon);
    }
    
    public String viewHours (int time){
        String strH = ""+time/60;
        String strM = ""+time%60;
            if(strH.length()==1)
                strH="0"+strH;
            
            if(strM.length()==1)
                strM="0"+strM;
                        
            String hm =  strH+":"+strM;
        
        return hm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLayeredPaneCadastro = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        txtObservacoes = new javax.swing.JTextField();
        cbxSimulador = new javax.swing.JComboBox();
        cbxFuncao = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtData = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##/##/####");  
            txtData = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtPousos = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        txtAerodromoOrigem = new javax.swing.JTextField();
        txtAerodromoDestino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNoturno = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##:##");  
            txtNoturno = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtDiurno = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##:##");  
            txtDiurno = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtNavegacao = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##:##");  
            txtNavegacao = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtCapota = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##:##");  
            txtCapota = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtInstrumento = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##:##");  
            txtInstrumento = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        btnSalvar = new javax.swing.JButton();
        jLayeredPaneRelatorio = new javax.swing.JLayeredPane();
        jScrollPaneRegistros = new javax.swing.JScrollPane();
        tblRegistros = new javax.swing.JTable();
        jScrollPaneTotais = new javax.swing.JScrollPane();
        tblTotais = new javax.swing.JTable();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLayeredPanePesquisaDetalhada = new javax.swing.JLayeredPane();
        jScrollPaneRegistros1 = new javax.swing.JScrollPane();
        tblRegistrosDetalhados = new javax.swing.JTable();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        txtDataPeriodo1 = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##/##/####");  
            txtData = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        txtDataPeriodo2 = new javax.swing.JFormattedTextField();
        try{  
            javax.swing.text.MaskFormatter horaMin = new javax.swing.text.MaskFormatter("##/##/####");  
            txtData = new javax.swing.JFormattedTextField(horaMin);  
        }  
        catch (Exception e){  
        }
        btnPesquisarPeriodo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemCadastro = new javax.swing.JMenuItem();
        jMenuItemRelatorios = new javax.swing.JMenuItem();
        jMenuItemPesquisaDetalhada = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPaneCadastro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de vôo"));
        jPanel1.setName(""); // NOI18N

        cbxSimulador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sim", "Não" }));
        cbxSimulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSimuladorActionPerformed(evt);
            }
        });

        cbxFuncao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Co-Piloto", "Instrutor de Vôo", "Piloto em Comando", "Piloto em Instrução" }));

        jLabel10.setText("Data");

        jLabel11.setText("Pousos");

        jLabel12.setText("Observações");

        jLabel13.setText("Simulador");

        jLabel14.setText("Função a bordo");

        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtPousos.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtPousos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPousosActionPerformed(evt);
            }
        });
        txtPousos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPousosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPousos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cbxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtObservacoes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14)
                    .addComponent(txtPousos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSimulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tempo de vôo"));

        txtAerodromoDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAerodromoDestinoActionPerformed(evt);
            }
        });

        jLabel1.setText("Matrícula");

        jLabel2.setText("Aérodromo de Origem");

        jLabel3.setText("Diúrno");

        jLabel4.setText("Navegação");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Habilitação");

        jLabel6.setText("Noturno");

        jLabel7.setText("Aérodromo de Destino");

        jLabel8.setText("Instrumento Real");

        jLabel9.setText("Sob capota");

        txtNoturno.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtNoturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoturnoActionPerformed(evt);
            }
        });
        txtNoturno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoturnoKeyReleased(evt);
            }
        });

        txtDiurno.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtDiurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiurnoActionPerformed(evt);
            }
        });
        txtDiurno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDiurnoKeyReleased(evt);
            }
        });

        txtNavegacao.setEnabled(false);
        txtNavegacao.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtNavegacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNavegacaoActionPerformed(evt);
            }
        });

        txtCapota.setEnabled(false);
        txtCapota.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCapota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapotaActionPerformed(evt);
            }
        });
        txtCapota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCapotaKeyReleased(evt);
            }
        });

        txtInstrumento.setEnabled(false);
        txtInstrumento.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstrumentoActionPerformed(evt);
            }
        });
        txtInstrumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInstrumentoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAerodromoOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(txtDiurno)
                    .addComponent(txtNavegacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAerodromoDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtCapota)
                            .addComponent(txtNoturno, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(txtInstrumento))
                        .addGap(50, 50, 50))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAerodromoOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtAerodromoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDiurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCapota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(80, 23));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPaneCadastroLayout = new javax.swing.GroupLayout(jLayeredPaneCadastro);
        jLayeredPaneCadastro.setLayout(jLayeredPaneCadastroLayout);
        jLayeredPaneCadastroLayout.setHorizontalGroup(
            jLayeredPaneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneCadastroLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(jLayeredPaneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPaneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jLayeredPaneCadastroLayout.setVerticalGroup(
            jLayeredPaneCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneCadastroLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPaneCadastro.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneCadastro.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneCadastro.setLayer(btnSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPaneRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPaneRelatorio.setPreferredSize(new java.awt.Dimension(777, 443));

        tblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPaneRegistros.setViewportView(tblRegistros);

        tblTotais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTotais.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPaneTotais.setViewportView(tblTotais);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Registros Lançados");

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Total");

        javax.swing.GroupLayout jLayeredPaneRelatorioLayout = new javax.swing.GroupLayout(jLayeredPaneRelatorio);
        jLayeredPaneRelatorio.setLayout(jLayeredPaneRelatorioLayout);
        jLayeredPaneRelatorioLayout.setHorizontalGroup(
            jLayeredPaneRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRegistros, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLayeredPaneRelatorioLayout.createSequentialGroup()
                .addGroup(jLayeredPaneRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 150, Short.MAX_VALUE))
        );
        jLayeredPaneRelatorioLayout.setVerticalGroup(
            jLayeredPaneRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneRelatorioLayout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPaneTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jLayeredPaneRelatorio.setLayer(jScrollPaneRegistros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRelatorio.setLayer(jScrollPaneTotais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRelatorio.setLayer(label1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRelatorio.setLayer(label2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPanePesquisaDetalhada.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPanePesquisaDetalhada.setPreferredSize(new java.awt.Dimension(777, 443));

        tblRegistrosDetalhados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegistrosDetalhados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPaneRegistros1.setViewportView(tblRegistrosDetalhados);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Período:");

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Registros Lançados");

        txtDataPeriodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPeriodo1ActionPerformed(evt);
            }
        });

        txtDataPeriodo2.setToolTipText("");
        txtDataPeriodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataPeriodo2ActionPerformed(evt);
            }
        });

        btnPesquisarPeriodo.setText("Pesquisar");
        btnPesquisarPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPeriodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPanePesquisaDetalhadaLayout = new javax.swing.GroupLayout(jLayeredPanePesquisaDetalhada);
        jLayeredPanePesquisaDetalhada.setLayout(jLayeredPanePesquisaDetalhadaLayout);
        jLayeredPanePesquisaDetalhadaLayout.setHorizontalGroup(
            jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPanePesquisaDetalhadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRegistros1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(jLayeredPanePesquisaDetalhadaLayout.createSequentialGroup()
                        .addGroup(jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPanePesquisaDetalhadaLayout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDataPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDataPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisarPeriodo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPanePesquisaDetalhadaLayout.setVerticalGroup(
            jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPanePesquisaDetalhadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPanePesquisaDetalhadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarPeriodo)))
                .addGap(15, 15, 15)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPaneRegistros1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );
        jLayeredPanePesquisaDetalhada.setLayer(jScrollPaneRegistros1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePesquisaDetalhada.setLayer(label3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePesquisaDetalhada.setLayer(label5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePesquisaDetalhada.setLayer(txtDataPeriodo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePesquisaDetalhada.setLayer(txtDataPeriodo2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePesquisaDetalhada.setLayer(btnPesquisarPeriodo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("jButton1");

        jMenu4.setText("Menu");

        jMenuItemCadastro.setText("Cadastro");
        jMenuItemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemCadastro);

        jMenuItemRelatorios.setText("Relatorios");
        jMenuItemRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRelatoriosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemRelatorios);

        jMenuItemPesquisaDetalhada.setText("Pesquisa Detalhada");
        jMenuItemPesquisaDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisaDetalhadaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemPesquisaDetalhada);

        jMenuBar.add(jMenu4);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLayeredPaneCadastro))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPaneRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPanePesquisaDetalhada, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addGap(70, 70, 70)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPaneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jLayeredPaneRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jLayeredPanePesquisaDetalhada, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(145, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        Registro reg = new Registro();
        Calendar data = null;

        try {
            Date date = new SimpleDateFormat("dd/MM/yyyy").parse(txtData.getText());
            data = Calendar.getInstance();
            data.setTime(date);
        } catch (Exception e) {
            out.println("Erro na conversão da data");
            return; //para a execução do método
        }

        reg.setData(data);
        reg.setPousos(Integer.parseInt(txtPousos.getText()));
        reg.setFuncao(cbxFuncao.getSelectedItem().toString());
        reg.setObservacoes(txtObservacoes.getText());
        reg.setSimulador(cbxSimulador.getSelectedItem().toString());
        reg.setMatricula(txtMatricula.getText());
        reg.setAerodromoOrigem(txtAerodromoOrigem.getText());
        reg.setDiurno(stringToMinutes(txtDiurno.getText()));
        reg.setNavegacao(stringToMinutes(txtNavegacao.getText()));
        reg.setAerodromoDestino(txtAerodromoDestino.getText());
        reg.setNoturno(stringToMinutes(txtNoturno.getText()));
        reg.setInstrumento(stringToMinutes(txtInstrumento.getText()));
        reg.setCapota(stringToMinutes(txtCapota.getText()));

        RegistroDao regDao = new RegistroDao();
        regDao.adiciona(reg);

        JOptionPane.showMessageDialog(null, "Inclusão efetuada com sucesso!");

        txtData.setText("");
        txtPousos.setText("");
        cbxFuncao.setSelectedIndex(0);
        txtObservacoes.setText("");
        cbxSimulador.setSelectedIndex(0);
        txtMatricula.setText("");
        txtAerodromoOrigem.setText("");
        txtAerodromoDestino.setText("");
        txtDiurno.setText("");
        txtNoturno.setText("");
        txtNavegacao.setText("");
        txtInstrumento.setText("");
        txtCapota.setText("");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtInstrumentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInstrumentoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstrumentoKeyReleased

    private void txtInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstrumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInstrumentoActionPerformed

    private void txtCapotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapotaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapotaKeyReleased

    private void txtCapotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapotaActionPerformed

    private void txtNavegacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNavegacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNavegacaoActionPerformed

    private void txtDiurnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiurnoKeyReleased
        // TODO add your handling code here:
        if(txtDiurno.getText().length() >= 5
            && !txtDiurno.getText().contains(" ")){
            txtNavegacao.setEnabled(true);
            txtInstrumento.setEnabled(true);
            txtCapota.setEnabled(true);
        }else{
            if(txtDiurno.getText().contains(" ")){
                txtNavegacao.setEnabled(false);
                txtInstrumento.setEnabled(false);
                txtCapota.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtDiurnoKeyReleased

    private void txtDiurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiurnoActionPerformed

    private void txtNoturnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoturnoKeyReleased
        // TODO add your handling code here:
        if(txtNoturno.getText().length() >= 5
            && !txtNoturno.getText().contains(" ")){
            txtNavegacao.setEnabled(true);
            txtInstrumento.setEnabled(true);
            txtCapota.setEnabled(true);
        }else{
            if(txtDiurno.getText().contains(" ")){
                txtNavegacao.setEnabled(false);
                txtInstrumento.setEnabled(false);
                txtCapota.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtNoturnoKeyReleased

    private void txtNoturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoturnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoturnoActionPerformed

    private void txtAerodromoDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAerodromoDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAerodromoDestinoActionPerformed

    private void txtPousosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPousosKeyReleased
        // TODO add your handling code here:
        txtPousos.setText(txtPousos.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_txtPousosKeyReleased

    private void txtPousosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPousosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPousosActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void cbxSimuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSimuladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSimuladorActionPerformed

    private void jMenuItemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroActionPerformed
        // TODO add your handling code here:       
        jLayeredPaneRelatorio.setVisible(false);
        jLayeredPaneCadastro.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastroActionPerformed

    private void jMenuItemRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRelatoriosActionPerformed
        // TODO add your handling code here:
        //Criacao das tabela
        tblRegistros.setAutoResizeMode(tblRegistros.AUTO_RESIZE_ALL_COLUMNS); 
        jScrollPaneRegistros.setPreferredSize(jScrollPaneRegistros.getParent().getPreferredSize());
        
        try{
            //Cria uma instancia da classe registro
           Registro reg = new Registro();
           tblRegistros.removeAll();

           this.connection = new ConnectionFactory().getConnection();
           ArrayList<Registro> regs = new ArrayList<Registro>();
           PreparedStatement stmt = (PreparedStatement) this.connection.
                           prepareStatement("select * from controlehoras");
           ResultSet rs = stmt.executeQuery();

           String[] colunas = new String[]{"Data", "Pousos", "Função a bordo", "Observações", "Simulador", "Matrícula", 
           "Aérodromo de Origem", "Aérodromo de Destino", "Diurno", "Noturno", "Navegação", "Instrumento Real", "Sob Capota"};
           String[] linha = new String[13];

           //"Model" para exibicao dos dados na tabela
           DefaultTableModel model = new DefaultTableModel(null, colunas);

           //Seta "model" como o modelo da tabela "tblResultado"
           tblRegistros.setModel(model);
           
           RegistroDao list = new RegistroDao();
           regs = list.getLista();

           for (Registro x : regs) {
               
                Calendar cal = new GregorianCalendar();
                cal = x.getData();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                dateFormat.setCalendar(cal); 
                linha[0] = (dateFormat.format(cal.getTime()));
                
                String strPousos = ""+x.getPousos();
                linha[1] = (strPousos);
                
                linha[2] = (x.getFuncao());
                linha[3] = (x.getObservacoes());
                linha[4] = (x.getSimulador());
                linha[5] = (x.getMatricula());
                linha[6] = (x.getAerodromoOrigem());
                linha[7] = (x.getAerodromoDestino());             
                linha[8] = (viewHours(x.getDiurno()));                                                                                     
                linha[9] = (viewHours(x.getNoturno()));
                linha[10] = (viewHours(x.getNavegacao()));
                linha[11] = (viewHours(x.getInstrumento()));
                linha[12] = (viewHours(x.getCapota()));
                              
                model.addRow(linha);       
           }
          
          /*for(int i=0; i<13; i++){*/ 
   
          //tblRegistros.getColumnModel().getColumn(5).setPreferredWidth(100);
          /*}*/
           
           tblRegistros.setFillsViewportHeight(true);
           
        }catch(SQLException e){
            
        }
        
        
        try{
            //Cria uma instancia da classe registro
           Registro total = new Registro();
           tblTotais.removeAll();
           

           String[] colunasTotais = new String[]{"Diurno", "Noturno", "Navegação", "Instrumento Real", "Sob Capota"};
           String[] linhaTotais = new String[5];

           //"Model" para exibicao dos dados na tabela
           DefaultTableModel modelTotais = new DefaultTableModel(null, colunasTotais);

           //Seta "model" como o modelo da tabela "tblResultado"
           tblTotais.setModel(modelTotais);
           
           RegistroDao listTotais = new RegistroDao();
           ArrayList<Registro> regsTotais = listTotais.getListaTotais();

           for(Registro x : regsTotais) {
                linhaTotais[0] = (viewHours(x.getDiurno()));                                                                                     
                linhaTotais[1] = (viewHours(x.getNoturno()));
                linhaTotais[2] = (viewHours(x.getNavegacao()));
                linhaTotais[3] = (viewHours(x.getInstrumento()));
                linhaTotais[4] = (viewHours(x.getCapota()));
                              
                modelTotais.addRow(linhaTotais);       
           }
          
          /*for(int i=0; i<13; i++){*/ 
   
          //tblRegistros.getColumnModel().getColumn(5).setPreferredWidth(100);
          /*}*/
           
           tblTotais.setFillsViewportHeight(true);
           
        }catch(Exception e){
            
        }
        
        jLayeredPaneCadastro.setVisible(false);
        jLayeredPanePesquisaDetalhada.setVisible(false);
        jLayeredPaneRelatorio.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemRelatoriosActionPerformed

    private void txtDataPeriodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPeriodo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPeriodo1ActionPerformed

    private void txtDataPeriodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataPeriodo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataPeriodo2ActionPerformed

    private void btnPesquisarPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPeriodoActionPerformed

        //Criacao das tabela
        tblRegistrosDetalhados.setAutoResizeMode(tblRegistros.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPaneRegistros.setPreferredSize(jScrollPaneRegistros.getParent().getPreferredSize());

        try{
            //Cria uma instancia da classe registro
            Registro reg = new Registro();
            tblRegistrosDetalhados.removeAll();

            this.connection = new ConnectionFactory().getConnection();
            ArrayList<Registro> regs = new ArrayList<Registro>();
            PreparedStatement stmt = (PreparedStatement) this.connection.
            prepareStatement("select * from controlehoras");
            ResultSet rs = stmt.executeQuery();

            String[] colunas = new String[]{"Data", "Pousos", "Função a bordo", "Observações", "Simulador", "Matrícula",
                "Aérodromo de Origem", "Aérodromo de Destino", "Diurno", "Noturno", "Navegação", "Instrumento Real", "Sob Capota"};
            String[] linha = new String[13];

            //"Model" para exibicao dos dados na tabela
            DefaultTableModel model = new DefaultTableModel(null, colunas);

            //Seta "model" como o modelo da tabela "tblResultado"
            tblRegistrosDetalhados.setModel(model);

            RegistroDao list = new RegistroDao();
            regs = list.getLista();

            for (Registro x : regs) {

                Calendar cal = new GregorianCalendar();
                cal = x.getData();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                dateFormat.setCalendar(cal);
                linha[0] = (dateFormat.format(cal.getTime()));

                String strPousos = ""+x.getPousos();
                linha[1] = (strPousos);

                linha[2] = (x.getFuncao());
                linha[3] = (x.getObservacoes());
                linha[4] = (x.getSimulador());
                linha[5] = (x.getMatricula());
                linha[6] = (x.getAerodromoOrigem());
                linha[7] = (x.getAerodromoDestino());
                linha[8] = (viewHours(x.getDiurno()));
                linha[9] = (viewHours(x.getNoturno()));
                linha[10] = (viewHours(x.getNavegacao()));
                linha[11] = (viewHours(x.getInstrumento()));
                linha[12] = (viewHours(x.getCapota()));

                model.addRow(linha);
            }

            /*for(int i=0; i<13; i++){*/

                //tblRegistros.getColumnModel().getColumn(5).setPreferredWidth(100);
                /*}*/

            tblRegistrosDetalhados.setFillsViewportHeight(true);

        }catch(SQLException e){

        }
    }//GEN-LAST:event_btnPesquisarPeriodoActionPerformed

    private void jMenuItemPesquisaDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisaDetalhadaActionPerformed
        // TODO add your handling code here:
        jLayeredPaneCadastro.setVisible(false);
        jLayeredPaneRelatorio.setVisible(false);
        jLayeredPanePesquisaDetalhada.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisaDetalhadaActionPerformed

    private int stringToMinutes(String str){
       try{
            int hours = Integer.parseInt(str.substring(0, 2))*60;
            int minutes = Integer.parseInt(str.substring(3, 5));
            int total = hours + minutes;
            return total;
       }catch(Exception e){
            return 0;
       }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Util.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){               
                Util utl = new Util();
                utl.jLayeredPaneRelatorio.setVisible(false);
                utl.jLayeredPanePesquisaDetalhada.setVisible(false);
                utl.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarPeriodo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxFuncao;
    private javax.swing.JComboBox cbxSimulador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPaneCadastro;
    private javax.swing.JLayeredPane jLayeredPanePesquisaDetalhada;
    private javax.swing.JLayeredPane jLayeredPaneRelatorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemCadastro;
    private javax.swing.JMenuItem jMenuItemPesquisaDetalhada;
    private javax.swing.JMenuItem jMenuItemRelatorios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneRegistros;
    private javax.swing.JScrollPane jScrollPaneRegistros1;
    private javax.swing.JScrollPane jScrollPaneTotais;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private javax.swing.JTable tblRegistros;
    private javax.swing.JTable tblRegistrosDetalhados;
    private javax.swing.JTable tblTotais;
    private javax.swing.JTextField txtAerodromoDestino;
    private javax.swing.JTextField txtAerodromoOrigem;
    private javax.swing.JFormattedTextField txtCapota;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JFormattedTextField txtDataPeriodo1;
    private javax.swing.JFormattedTextField txtDataPeriodo2;
    private javax.swing.JFormattedTextField txtDiurno;
    private javax.swing.JFormattedTextField txtInstrumento;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JFormattedTextField txtNavegacao;
    private javax.swing.JFormattedTextField txtNoturno;
    private javax.swing.JTextField txtObservacoes;
    private javax.swing.JFormattedTextField txtPousos;
    // End of variables declaration//GEN-END:variables
}
